#by Muhammad Hazim Bin Abdullah B24CS0027
# Playbook A
# Configure router interface and create local administrator account

---
- name: Configure IP Address and Create User Account
  hosts: routers
  gather_facts: false

  tasks:
  
# Configure GigabitEthernet1 IP address
    - name: Configure IP Address
      cisco.ios.ios_config:
        parents: interface GigabitEthernet1
        lines:
          - ip address 192.168.56.101 255.255.255.0
          - no shutdown
          
# Create administrator account
    - name: Create Local User Account
      cisco.ios.ios_config:
        lines:
          - username admin privilege 15 secret Cisco123

    - name: Verify Router Interface Configuration
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: interface_output

    - name: Verify Local User Account
      cisco.ios.ios_command:
        commands:
          - show running-config | include username
      register: user_output

    - name: Display Interface Information
      debug:
        msg: "{{ interface_output.stdout_lines }}"

    - name: Display User Information
      debug:
        msg: "{{ user_output.stdout_lines }}"