---
- name: Configure Banner and Interface description
  hosts: routers
  gather_facts: false

  tasks:
    - name: Set MOTD Banner message
      cisco.ios.ios_banner:
        banner: motd
        text: "WARNING: Authorized Access Only. Configured by HUZSA."
        state: present

    - name: Add Interface description
      cisco.ios.ios_config:
        lines:
          - description Ansible Configured Interface
        parents: interface GigabitEthernet1

    - name: Verify Banner Configuration
      cisco.ios.ios_command:
        commands:
          - show running-config | section banner
      register: banner_output

    - name: Verify Interface Description
      cisco.ios.ios_command:
        commands:
          - show running-config interface GigabitEthernet1
      register: interface_output

    - name: Display Banner
      debug:
        msg: "{{ banner_output.stdout_lines }}"

    - name: Display Interface Description
      debug:
        msg: "{{ interface_output.stdout_lines }}"
